driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
    run_list: apt::default
  - name: debian-8
    run_list: apt::default
  - name: fedora-26
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: client
    run_list:
      - recipe[subversion::client]
  - name: server
    run_list:
      - recipe[subversion::server]
