driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.7

suites:
  - name: client
    run_list:
      - recipe[subversion::client]
  - name: server
    run_list:
      - recipe[subversion::server]
