addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
    #  - INSTANCE=client-amazonlinux
  - INSTANCE=client-centos-6
  - INSTANCE=client-centos-7
  - INSTANCE=client-debian-8
  - INSTANCE=client-debian-9
  - INSTANCE=client-fedora-latest
  - INSTANCE=client-ubuntu-1604
    #- INSTANCE=server-amazonlinux
  - INSTANCE=server-centos-6
  - INSTANCE=server-centos-7
  - INSTANCE=server-debian-8
  - INSTANCE=server-debian-9
  #- INSTANCE=server-fedora-latest # Disabled due to apache2 cookbook being broken on fedora
  - INSTANCE=server-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
